; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only
;
; package.yml passes /DMyAppVersion /DPublishDir /DInstallerOutputDir /DSetupIconPath.
; Keep #ifndef so a local compile still uses the OneDrive defaults below.
; Forward slashes: ISPP treats \ as an escape, so "C:\Users\..." would drop the slash.

#define MyAppName "RHI"
#ifndef PublishDir
  #define PublishDir SourcePath + "RenoDXCommander/bin/installer/publish"
#endif
#ifndef InstallerOutputDir
  #define InstallerOutputDir SourcePath + "RenoDXCommander/bin/installer"
#endif
#ifndef MyAppVersion
  #define MyAppVersion GetVersionNumbersString(PublishDir + "/RHI.exe")
#endif
#ifndef SetupIconPath
  #define SetupIconPath PublishDir + "/icon.ico"
#endif
#define MyAppPublisher "RankFTW"
#define MyAppURL "www.github.com/rankftw"
#define MyAppExeName "RHI.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{05342962-55F5-4BA3-BFD3-DBA01D2B8BCB}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir={#InstallerOutputDir}
OutputBaseFilename=RHI-Setup
SetupIconFile={#SetupIconPath}
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#PublishDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[UninstallDelete]
Type: filesandordirs; Name: "{localappdata}\RHI"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent; BeforeInstall: BeginForegroundHandoff; AfterInstall: CompleteForegroundHandoff

[Code]
// Shared protocol names with Services/ForegroundActivation.cs. Discover the
// window rather than the launch PID: Admin Mode may replace the initial process.
const
  ForegroundReadyProperty = 'RHI.ForegroundReady.v1';
  ForegroundRequestMessage = 'RHI.ForegroundRequest.v1';

var
  ForegroundProgress: TOutputProgressWizardPage;

// Inno Setup 6 runs a 32-bit installer, even with x64compatible installation mode.
function FindNextTopLevelWindow(Parent, AfterWindow: HWND; ClassName, WindowName: Longint): HWND;
  external 'FindWindowExW@user32.dll stdcall';
function ReadWindowProperty(Window: HWND; Name: String): THandle;
  external 'GetPropW@user32.dll stdcall';
function ReadWindowProcessId(Window: HWND; var ProcessId: DWORD): DWORD;
  external 'GetWindowThreadProcessId@user32.dll stdcall';
function OpenTargetProcess(Access: DWORD; InheritHandle: BOOL; ProcessId: DWORD): THandle;
  external 'OpenProcess@kernel32.dll stdcall';
function ReadProcessImage(Process: THandle; Flags: DWORD; FileName: String; var Size: DWORD): BOOL;
  external 'QueryFullProcessImageNameW@kernel32.dll stdcall';
function CloseTargetHandle(Handle: THandle): BOOL;
  external 'CloseHandle@kernel32.dll stdcall';
function GrantForegroundPermission(ProcessId: DWORD): BOOL;
  external 'AllowSetForegroundWindow@user32.dll stdcall';
function RegisterForegroundMessage(Name: String): UINT;
  external 'RegisterWindowMessageW@user32.dll stdcall';
function PostForegroundMessage(Window: HWND; Message: UINT; WParam: LongWord; LParam: Longint): BOOL;
  external 'PostMessageW@user32.dll stdcall';

function IsInstalledRhiProcess(ProcessId: DWORD): Boolean;
var
  Process: THandle;
  ImagePath: String;
  Size: DWORD;
begin
  Result := False;
  // PROCESS_QUERY_LIMITED_INFORMATION: works for both regular and elevated RHI.
  Process := OpenTargetProcess($1000, False, ProcessId);
  if Process = 0 then Exit;
  try
    Size := 32768;
    SetLength(ImagePath, Size);
    if ReadProcessImage(Process, 0, ImagePath, Size) then
    begin
      SetLength(ImagePath, Size);
      Result := CompareText(ImagePath, ExpandConstant('{app}\{#MyAppExeName}')) = 0;
    end;
  finally
    CloseTargetHandle(Process);
  end;
end;

function FindReadyRhiWindow(var ProcessId: DWORD): HWND;
var
  Window: HWND;
begin
  Result := 0;
  Window := FindNextTopLevelWindow(0, 0, 0, 0);
  while Window <> 0 do
  begin
    if ReadWindowProperty(Window, ForegroundReadyProperty) = 1 then
    begin
      ProcessId := 0;
      ReadWindowProcessId(Window, ProcessId);
      if (ProcessId <> 0) and IsInstalledRhiProcess(ProcessId) then
      begin
        Result := Window;
        Exit;
      end;
    end;
    Window := FindNextTopLevelWindow(0, Window, 0, 0);
  end;
end;

procedure BeginForegroundHandoff;
begin
  ForegroundProgress := CreateOutputProgressPage('Starting RHI', 'Waiting for the application window...');
  ForegroundProgress.SetText('Starting RHI (including Admin Mode, if enabled)...', '');
  ForegroundProgress.Show;
end;

procedure CompleteForegroundHandoff;
var
  Window: HWND;
  ProcessId, CurrentProcessId: DWORD;
  Message: UINT;
  Attempt: Integer;
begin
  Window := 0;
  ProcessId := 0;
  try
    // Bounded wait for readiness. SetProgress services the wizard's messages;
    // no synchronous calls are made into RHI's UI thread.
    for Attempt := 0 to 199 do
    begin
      ForegroundProgress.SetProgress(Attempt, 200);
      Window := FindReadyRhiWindow(ProcessId);
      if Window <> 0 then Break;
      Sleep(50);
    end;
  finally
    ForegroundProgress.Hide;
  end;

  if Window = 0 then
  begin
    Log('RHI foreground handoff: no ready window within 10 seconds; normal activation remains available.');
    Exit;
  end;

  // Revalidate after pumping messages, before granting permission.
  CurrentProcessId := 0;
  ReadWindowProcessId(Window, CurrentProcessId);
  if (CurrentProcessId <> ProcessId) or not IsInstalledRhiProcess(ProcessId) then Exit;
  Message := RegisterForegroundMessage(ForegroundRequestMessage);
  if Message = 0 then Exit;

  if GrantForegroundPermission(ProcessId) then
    Log(Format('RHI foreground permission granted to PID %d.', [ProcessId]))
  else
    Log(Format('RHI foreground permission refused for PID %d; RHI will use taskbar attention if necessary.', [ProcessId]));

  // Do not let the installer regain focus after delivering the request.
  WizardForm.Hide;
  if not PostForegroundMessage(Window, Message, 0, 0) then
    Log('RHI foreground handoff: could not post activation request.');
end;

function IsRhiRunning(): Boolean;
var
  WMI: Variant;
  Procs: Variant;
begin
  Result := False;
  try
    WMI := CreateOleObject('WbemScripting.SWbemLocator');
    WMI := WMI.ConnectServer('.', 'root\cimv2');
    Procs := WMI.ExecQuery('SELECT * FROM Win32_Process WHERE Name="RHI.exe"');
    Result := (Procs.Count > 0);
  except
  end;
end;

function InitializeSetup(): Boolean;
var
  SignalDir, SignalPath: String;
  WaitCount: Integer;
begin
  Result := True;

  // Only signal if RHI is actually running
  if not IsRhiRunning() then Exit;

  // Write shutdown signal file to %LocalAppData%\RHI\
  SignalDir := ExpandConstant('{localappdata}\RHI');
  if not DirExists(SignalDir) then
    ForceDirectories(SignalDir);
  SignalPath := SignalDir + '\rhi_shutdown_requested';
  SaveStringToFile(SignalPath, 'update', False);

  // Wait up to 10 seconds for RHI to close itself
  WaitCount := 0;
  while (WaitCount < 20) and IsRhiRunning() do
  begin
    Sleep(500);
    WaitCount := WaitCount + 1;
  end;

  // Never leave a request for the newly installed process to consume on launch.
  DeleteFile(SignalPath);

  // If still running, Inno's default CloseApplications will handle it
end;

