; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only
;
; package.yml passes /DMyAppVersion /DPublishDir /DInstallerOutputDir /DSetupIconPath.
; Keep #ifndef so a local compile still uses the OneDrive defaults below.
; Forward slashes: ISPP treats \ as an escape, so "C:\Users\..." would drop the slash.

#define MyAppName "RHI"
#ifndef MyAppVersion
  #define MyAppVersion "2.0.1"
#endif
#ifndef PublishDir
  #define PublishDir "C:/Users/Mark/OneDrive/Documents/RDXC/Publish/RHI"
#endif
#ifndef InstallerOutputDir
  #define InstallerOutputDir "C:/Users/Mark/OneDrive/Documents/RDXC/Installers"
#endif
#ifndef SetupIconPath
  #define SetupIconPath "C:/Users/Mark/OneDrive/Documents/RDXC/icon.ico"
#endif
#define MyAppPublisher "RankFTW"
#define MyAppURL "www.github.com/rankftw"
#define MyAppExeName "RHI.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{05342962-55F5-4BA3-BFD3-DBA01D2B8BCB}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only).
;PrivilegesRequired=lowest
OutputDir={#InstallerOutputDir}
OutputBaseFilename=RHI-Setup
SetupIconFile={#SetupIconPath}
SolidCompression=yes
WizardStyle=modern dynamic

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "{#PublishDir}\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "{#PublishDir}\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[UninstallDelete]
Type: filesandordirs; Name: "{localappdata}\RHI"

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Code]
function IsRhiRunning(): Boolean;
var
  WMI: Variant;
  Procs: Variant;
begin
  Result := False;
  try
    WMI := CreateOleObject('WbemScripting.SWbemLocator');
    WMI := WMI.ConnectServer('.', 'root\cimv2');
    Procs := WMI.ExecQuery('SELECT * FROM Win32_Process WHERE Name="RHI.exe"');
    Result := (Procs.Count > 0);
  except
  end;
end;

function InitializeSetup(): Boolean;
var
  SignalDir, SignalPath: String;
  WaitCount: Integer;
begin
  Result := True;

  // Only signal if RHI is actually running
  if not IsRhiRunning() then Exit;

  // Write shutdown signal file to %LocalAppData%\RHI\
  SignalDir := ExpandConstant('{localappdata}\RHI');
  if not DirExists(SignalDir) then
    ForceDirectories(SignalDir);
  SignalPath := SignalDir + '\rhi_shutdown_requested';
  SaveStringToFile(SignalPath, 'update', False);

  // Wait up to 10 seconds for RHI to close itself
  WaitCount := 0;
  while (WaitCount < 20) and IsRhiRunning() do
  begin
    Sleep(500);
    WaitCount := WaitCount + 1;
  end;

  // If still running, Inno's default CloseApplications will handle it
end;

